def nbaTriCode_dict():
    triCode_dict = {
    'PHI': '76ers',
    'MIL': 'Bucks',
    'CHI': 'Bulls',
    'CLE': 'Cavaliers',
    'BOS': 'Celtics',
    'LAC': 'Clippers',
    'MEM': 'Grizzlies',
    'ATL': 'Hawks',
    'MIA': 'Heat',
    'CHA': 'Hornets',
    'UTA': 'Jazz',
    'SAC': 'Kings',
    'NYK': 'Knicks',
    'LAL': 'Lakers',
    'ORL': 'Magic',
    'DAL': 'Mavericks',
    'BKN': 'Nets',
    'DEN': 'Nuggets',
    'IND': 'Pacers',
    'NOP': 'Pelicans',
    'DET': 'Pistons',
    'TOR': 'Raptors',
    'HOU': 'Rockets',
    'SAS': 'Spurs',
    'PHX': 'Suns',
    'OKC': 'Thunder',
    'MIN': 'Timberwolves',
    'POR': 'Trailblazers',
    'GSW': 'Warriors',
    'WAS': 'Wizards'
    }
    return(triCode_dict)
